# Configuration file for Anweddol client
#
# This document contains all of the configurations that the client 
# will be using. Comment or un-comment variables to change their 
# default values. Refer to the units explanations below, 
# and the official anweddol client documentation.

# Credentials database path
session_credentials_db_file_path: session_credentials_path
container_credentials_db_file_path: container_credentials_path
access_token_db_file_path: access_token_path

# RSA keys root path
rsa_keys_root_path: rsa_keys_path

# Generate RSA key pair on start and ignore the stored one
# Enabled by default for privacy matters
enable_onetime_rsa_keys: True
